// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RH_DELIRIO.Data;

namespace RH_DELIRIO.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220430000137_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.Admissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("data_admissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admissao");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.Bancos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("agencia_banco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("conta_banco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descricao_banco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numero_banco")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bancos");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.Cargos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("abreviacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("diasexp")
                        .HasColumnType("int");

                    b.Property<int>("diasprorr")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.Divisao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numero_divisao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Divisao");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.EnderecoFuncionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.Property<string>("rua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("unidade_federacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("unidade_federacaoId");

                    b.ToTable("EnderecoFuncionario");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.EnderecoLojas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.Property<string>("rua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EnderecoLojas");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.EstadoCivil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("EstadoCivil");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.Eventos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("data_evento")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao_evento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numero_evento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.Familiares", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("nasc_filho")
                        .HasColumnType("datetime2");

                    b.Property<string>("nome_filho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_mae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_pai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Familiares");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("admissaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("afastamento")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("bancoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("banco_pis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("cargo_atualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("cargo_originalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("carteira_trabalho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("causa_afastamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cidade_nascimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("desconto_sindicato")
                        .HasColumnType("bit");

                    b.Property<Guid?>("divisaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("emissao_ct")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("enderecoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("estado_civilId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("expedicao")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("familiaresId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("historico_feriasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("historico_funcionarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("historico_salarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("horarios_atuaisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("horarios_originaisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("instrucaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("loja_anteriorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("loja_atualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("loja_originalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("motivos_afastamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("nascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("naturalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_guerra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("orgao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pis_pasep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("plano_saudeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("registro_contador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("saida")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("salarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("secao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serie_ct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tamanho_calca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tamanho_camisa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titulo_eleitor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("uf_ctId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("uf_nascimentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("uf_rgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("uf_tituloId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("vtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("zona")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("admissaoId");

                    b.HasIndex("bancoId");

                    b.HasIndex("cargo_atualId");

                    b.HasIndex("cargo_originalId");

                    b.HasIndex("divisaoId");

                    b.HasIndex("enderecoId");

                    b.HasIndex("estado_civilId");

                    b.HasIndex("familiaresId");

                    b.HasIndex("historico_feriasId");

                    b.HasIndex("historico_funcionarioId");

                    b.HasIndex("historico_salarioId");

                    b.HasIndex("horarios_atuaisId");

                    b.HasIndex("horarios_originaisId");

                    b.HasIndex("instrucaoId");

                    b.HasIndex("loja_anteriorId");

                    b.HasIndex("loja_atualId");

                    b.HasIndex("loja_originalId");

                    b.HasIndex("motivos_afastamentoId");

                    b.HasIndex("plano_saudeId");

                    b.HasIndex("salarioId");

                    b.HasIndex("uf_ctId");

                    b.HasIndex("uf_nascimentoId");

                    b.HasIndex("uf_rgId");

                    b.HasIndex("uf_tituloId");

                    b.HasIndex("vtId");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.HistoricoFerias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("abonoferias")
                        .HasColumnType("int");

                    b.Property<DateTime>("datafim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("datagozo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("datainicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("diasgozo")
                        .HasColumnType("int");

                    b.Property<int>("diasvendidos")
                        .HasColumnType("int");

                    b.Property<int>("valorferias")
                        .HasColumnType("int");

                    b.Property<int>("valorvendido")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HistoricoFerias");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.HistoricoFuncionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HistoricoFuncionario");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.HistoricoSalario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("data_mod_salario")
                        .HasColumnType("datetime2");

                    b.Property<int>("salario_atual")
                        .HasColumnType("int");

                    b.Property<int>("salario_inicial")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HistoricoSalario");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.HorariosAtuais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("data_entrada_abertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_entrada_inter")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_entrada_noite")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_saida_abertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_saida_inter")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_saida_noite")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HorariosAtuais");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.HorariosOriginais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("data_entrada_abertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_entrada_inter")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_entrada_noite")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_saida_abertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_saida_inter")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_saida_noite")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HorariosOriginais");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.Instrucao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instrucao");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.Lojas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cod_amil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("endereco_lojasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("inscricao_estadual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("razao_social")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sigla")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("endereco_lojasId");

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.MotivosAfastamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("data_afastamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MotivosAfastamento");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.PlanoDeSaude", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("plano")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlanoDeSaude");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.Salarios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cargo_atual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargo_original")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("data_modificao")
                        .HasColumnType("datetime2");

                    b.Property<int>("salario_atual")
                        .HasColumnType("int");

                    b.Property<int>("salario_original")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Salarios");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.TarifasDeOnibus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("data_modificacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("tarifa_atual")
                        .HasColumnType("int");

                    b.Property<int>("tarifa_original")
                        .HasColumnType("int");

                    b.Property<string>("tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TarifasDeOnibus");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.UnidadeDeFederacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnidadeDeFederacao");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RH_DELIRIO.Models.EnderecoFuncionario", b =>
                {
                    b.HasOne("RH_DELIRIO.Models.UnidadeDeFederacao", "unidade_federacao")
                        .WithMany()
                        .HasForeignKey("unidade_federacaoId");

                    b.Navigation("unidade_federacao");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.Funcionario", b =>
                {
                    b.HasOne("RH_DELIRIO.Models.Admissao", "admissao")
                        .WithMany()
                        .HasForeignKey("admissaoId");

                    b.HasOne("RH_DELIRIO.Models.Bancos", "banco")
                        .WithMany()
                        .HasForeignKey("bancoId");

                    b.HasOne("RH_DELIRIO.Models.Cargos", "cargo_atual")
                        .WithMany()
                        .HasForeignKey("cargo_atualId");

                    b.HasOne("RH_DELIRIO.Models.Cargos", "cargo_original")
                        .WithMany()
                        .HasForeignKey("cargo_originalId");

                    b.HasOne("RH_DELIRIO.Models.Divisao", "divisao")
                        .WithMany()
                        .HasForeignKey("divisaoId");

                    b.HasOne("RH_DELIRIO.Models.EnderecoFuncionario", "endereco")
                        .WithMany()
                        .HasForeignKey("enderecoId");

                    b.HasOne("RH_DELIRIO.Models.EstadoCivil", "estado_civil")
                        .WithMany()
                        .HasForeignKey("estado_civilId");

                    b.HasOne("RH_DELIRIO.Models.Familiares", "familiares")
                        .WithMany()
                        .HasForeignKey("familiaresId");

                    b.HasOne("RH_DELIRIO.Models.HistoricoFerias", "historico_ferias")
                        .WithMany()
                        .HasForeignKey("historico_feriasId");

                    b.HasOne("RH_DELIRIO.Models.HistoricoFuncionario", "historico_funcionario")
                        .WithMany()
                        .HasForeignKey("historico_funcionarioId");

                    b.HasOne("RH_DELIRIO.Models.HistoricoSalario", "historico_salario")
                        .WithMany()
                        .HasForeignKey("historico_salarioId");

                    b.HasOne("RH_DELIRIO.Models.HorariosAtuais", "horarios_atuais")
                        .WithMany()
                        .HasForeignKey("horarios_atuaisId");

                    b.HasOne("RH_DELIRIO.Models.HorariosOriginais", "horarios_originais")
                        .WithMany()
                        .HasForeignKey("horarios_originaisId");

                    b.HasOne("RH_DELIRIO.Models.Instrucao", "instrucao")
                        .WithMany()
                        .HasForeignKey("instrucaoId");

                    b.HasOne("RH_DELIRIO.Models.Lojas", "loja_anterior")
                        .WithMany()
                        .HasForeignKey("loja_anteriorId");

                    b.HasOne("RH_DELIRIO.Models.Lojas", "loja_atual")
                        .WithMany()
                        .HasForeignKey("loja_atualId");

                    b.HasOne("RH_DELIRIO.Models.Lojas", "loja_original")
                        .WithMany()
                        .HasForeignKey("loja_originalId");

                    b.HasOne("RH_DELIRIO.Models.MotivosAfastamento", "motivos_afastamento")
                        .WithMany()
                        .HasForeignKey("motivos_afastamentoId");

                    b.HasOne("RH_DELIRIO.Models.PlanoDeSaude", "plano_saude")
                        .WithMany()
                        .HasForeignKey("plano_saudeId");

                    b.HasOne("RH_DELIRIO.Models.Salarios", "salario")
                        .WithMany()
                        .HasForeignKey("salarioId");

                    b.HasOne("RH_DELIRIO.Models.UnidadeDeFederacao", "uf_ct")
                        .WithMany()
                        .HasForeignKey("uf_ctId");

                    b.HasOne("RH_DELIRIO.Models.UnidadeDeFederacao", "uf_nascimento")
                        .WithMany()
                        .HasForeignKey("uf_nascimentoId");

                    b.HasOne("RH_DELIRIO.Models.UnidadeDeFederacao", "uf_rg")
                        .WithMany()
                        .HasForeignKey("uf_rgId");

                    b.HasOne("RH_DELIRIO.Models.UnidadeDeFederacao", "uf_titulo")
                        .WithMany()
                        .HasForeignKey("uf_tituloId");

                    b.HasOne("RH_DELIRIO.Models.TarifasDeOnibus", "vt")
                        .WithMany()
                        .HasForeignKey("vtId");

                    b.Navigation("admissao");

                    b.Navigation("banco");

                    b.Navigation("cargo_atual");

                    b.Navigation("cargo_original");

                    b.Navigation("divisao");

                    b.Navigation("endereco");

                    b.Navigation("estado_civil");

                    b.Navigation("familiares");

                    b.Navigation("historico_ferias");

                    b.Navigation("historico_funcionario");

                    b.Navigation("historico_salario");

                    b.Navigation("horarios_atuais");

                    b.Navigation("horarios_originais");

                    b.Navigation("instrucao");

                    b.Navigation("loja_anterior");

                    b.Navigation("loja_atual");

                    b.Navigation("loja_original");

                    b.Navigation("motivos_afastamento");

                    b.Navigation("plano_saude");

                    b.Navigation("salario");

                    b.Navigation("uf_ct");

                    b.Navigation("uf_nascimento");

                    b.Navigation("uf_rg");

                    b.Navigation("uf_titulo");

                    b.Navigation("vt");
                });

            modelBuilder.Entity("RH_DELIRIO.Models.Lojas", b =>
                {
                    b.HasOne("RH_DELIRIO.Models.EnderecoLojas", "endereco_lojas")
                        .WithMany()
                        .HasForeignKey("endereco_lojasId");

                    b.Navigation("endereco_lojas");
                });
#pragma warning restore 612, 618
        }
    }
}
